configuroselector

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,173 +1,343 @@
-name: 'Generic Build and Push'
-description: 'Build y push de imagen de docker'
+name: 'Build and Push Multi Organización'
+description: 'Selecciona la mejor estrategia de build and push según los datos proporcionados'
 inputs:
 # ACR Datas
-  ACR_USERNAME:
-    description: "user de acr"
+  REGISTRY_DATA:
+    description: "Json de datos de registry principal"
     required: true
-  ACR_PASSWORD:
-    description: "password de acr"
-    required: true
-  ACR_NAME:
-    description: "nombre del acr"
-    required: true
-  ACR_FULL_NAME:
-    description: "nombre del acr con azurecr.io"
-    required: true
-#ACR WW Datas 
-  ACR_USERNAMEWW:
-    description: "user de acr"
-    required: true
-  ACR_PASSWORDWW:
-    description: "password de acr"
-    required: true
-  ACR_NAMEWW:
-    description: "nombre del acr"
-    required: true
-  ACR_FULL_NAMEWW:
-    description: "nombre del acr con azurecr.io"
-    required: true
-#ECR HOP Datas
-  ECR_ID:
-    description: "user de acr"
-    required: true
-  ECR_PASSWORD:
-    description: "password de acr"
-    required: true
-  SWR_USERNAME:
-    description: "user de acr"
-    required: true
-  SWR_PASSWORD:
-    description: "password de acr"
-    required: true
-  SWR_NAME:
-    description: "nombre de la organizacion de SWR"
-    required: true
-  SWR_URL:
-    description: "url de swr"
-    required: true
+  REGISTRY_DATA2:
+    description: "Json de datos de registry 2"
+    required: false
+    default: "[]"
+  REGISTRY_DATA3:
+    description: "Json de datos de registry 3"
+    required: false
+    default: "[]"
+  REGISTRY_DATA4:
+    description: "Json de datos de registry 4"
+    required: false
+    default: "[]"
+  REGISTRY_SELECTOR:
+    description: "Tipo de registry seleccionada"
+    required: false
+    default: "acr"
+  WORKFLOW_CD:
+    description: "Variable que define el tipo de pipeline que es (Standard -> Normal Andreani 2 registries)"
+    required: false
+    default: "standard" 
+
 
   ## App Datas
-  appName:
-    description: "Nombre de la aplicacion (dentro del proyecto)"
-    required: true
-  teamProject:
-    description: "Nombre del proyecto/equipo"
+  appdataJson:
+    description: "Json de datos de la aplicación"
     required: true
   appVersion:
     description: "tag para subir imagen"
     required: true
   matrix_deploy:
-    description: "deploy en multiples ambientes"
+    description: "Listado de sufijos para generación de multiples instancias"
     required: false
     default: "[]"
-  
-  andreani:
-    description: "Se pushea a la registry de Andreani"
-    required: false
-    type: boolean
-    default: true
-  witwot:
-    description: "Se pushea a la registry de Witwot"
-    required: true
-    type: boolean
-    default: false
-  hop:
-    description: "Se pushea a la registry de HOP"
-    required: true
-    type: boolean
-    default: false
 
+## Es medio monolítico para aprovechar una misma acción de build y luego hacer los pushes necesarios
 
 runs:
   using: "composite"
   steps:
-      - name: Generate Docker Tags
-        id: tags
-        uses: actions/github-script@v7
-        with:
-          script: |
-            let tags = [];
-            let matrix_deploy = ${{ inputs.matrix_deploy }};
-            if (matrix_deploy.length > 0) {
-              matrix_deploy.forEach(deploy => {
-                let tag = `${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}-${deploy}:${{ inputs.appVersion}}`
-                tags.push(tag);
-              });
-            } else {
-              tags.push(`${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}:${{ inputs.appVersion}}`);
-            }
-            tags.push(`${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}:ultima`);
-            return tags.join('\n');
-          result-encoding: string
+    - name: Extract variables to use 
+      shell: bash
+      env:
+        REGISTRY_DATA: ${{ inputs.REGISTRY_DATA }}
+        REGISTRY_DATA2: ${{ inputs.REGISTRY_DATA2 }}
+        REGISTRY_DATA3: ${{ inputs.REGISTRY_DATA3 }}
+        REGISTRY_DATA4: ${{ inputs.REGISTRY_DATA4 }}
+        REGISTRY_SELECTOR: ${{ inputs.REGISTRY_SELECTOR }}
+        WORKFLOW: ${{ inputs.WORKFLOW_CD }}
+      run: |-
+        #Conformamos las variables para cada caso de WORKFLOW_CD
+        if [[ "$WORKFLOW" == "standard" || "$WORKFLOW" == "dms" ]]; then
+          printf '%s' "$REGISTRY_DATA" > reg_content.txt
+          ACR_USERNAME=$(jq -r '.ACR_USERNAME' reg_content.txt)
+          ACR_PASSWORD=$(jq -r '.ACR_PASSWORD' reg_content.txt)
+          REGISTRY_PASS=$(jq -r '.REGISTRY_PASS' reg_content.txt)
+          ACR_FULL_NAME=$(jq -r '.ACR_FULL_NAME' reg_content.txt)
+          ACR_NAME=$(jq -r '.ACR_NAME' reg_content.txt)
 
-      - name: "Debug echos"
-        id: version
-        shell: bash
-        run: |
-              echo "Tags Creados"
-              echo "${{ steps.tags.outputs.result }}"
+          echo "ACR_USERNAME=$ACR_USERNAME" >> "$GITHUB_ENV"
+          echo "ACR_PASSWORD=$ACR_PASSWORD" >> "$GITHUB_ENV"
+          echo "REGISTRY_PASS=$REGISTRY_PASS" >> "$GITHUB_ENV"
+          echo "ACR_FULL_NAME=$ACR_FULL_NAME" >> "$GITHUB_ENV"
+          echo "ACR_NAME=$ACR_NAME" >> "$GITHUB_ENV"
+          rm -f reg_content.txt
 
+          printf '%s' "$REGISTRY_DATA2" > reg_content.txt
+          ECR_ID=$(jq -r '.ECR_ID' reg_content.txt)
+          ECR_PASSWORD=$(jq -r '.ECR_PASSWORD' reg_content.txt)
+          ECR_FULLNAME=$(jq -r '.ECR_FULLNAME' reg_content.txt)
+          echo "ECR_ID=$ECR_ID" >> "$GITHUB_ENV"
+          echo "ECR_PASSWORD=$ECR_PASSWORD" >> "$GITHUB_ENV"
+          echo "ECR_FULLNAME=$ECR_FULLNAME" >> "$GITHUB_ENV"     
+          rm -f reg_content.txt
+        elif [[ "$WORKFLOW" == "hop" ]]; then
+          printf '%s' "$REGISTRY_DATA" > reg_content.txt
+          ECR_IDHOP=$(jq -r '.ECR_ID' reg_content.txt)
+          ECR_PASSWORDHOP=$(jq -r '.ECR_PASSWORD' reg_content.txt)
+          ECR_FULLNAMEHOP=$(jq -r '.ECR_FULLNAME' reg_content.txt)
+          echo "ECR_IDHOP=$ECR_ID" >> "$GITHUB_ENV"
+          echo "ECR_PASSWORDHHOP=$ECR_PASSWORD" >> "$GITHUB_ENV"
+          echo "ECR_FULLNAMEHOP=$ECR_FULLNAME" >> "$GITHUB_ENV"
+          rm -f reg_content.txt
+        elif [[ "$WORKFLOW" == "witwot" ]]; then
+          printf '%s' "$REGISTRY_DATA" > reg_content.txt
+          ACR_USERNAMEWW=$(jq -r '.ACR_USERNAME' reg_content.txt)
+          ACR_PASSWORDWW=$(jq -r '.ACR_PASSWORD' reg_content.txt)
+          REGISTRY_PASSWW=$(jq -r '.REGISTRY_PASS' reg_content.txt)
+          ACR_FULL_NAMEWW=$(jq -r '.ACR_FULL_NAME' reg_content.txt)
+          ACR_NAME=$(jq -r '.ACR_NAME' reg_content.txt)
+          echo "ACR_USERNAMEWW=$ACR_USERNAME" >> "$GITHUB_ENV"
+          echo "ACR_PASSWORDWW=$ACR_PASSWORD" >> "$GITHUB_ENV"
+          echo "REGISTRY_PASSWW=$REGISTRY_PASS" >> "$GITHUB_ENV"
+          echo "ACR_FULL_NAMEWW=$ACR_FULL_NAME" >> "$GITHUB_ENV"
+          echo "ACR_NAMEWW=$ACR_NAME" >> "$GITHUB_ENV"
+          rm -f reg_content.txt
+        elif [[ "$WORKFLOW" == "multiorg" ]]; then
+          printf '%s' "$REGISTRY_DATA" > reg_content.txt
+          ACR_USERNAME=$(jq -r '.ACR_USERNAME' reg_content.txt)
+          ACR_PASSWORD=$(jq -r '.ACR_PASSWORD' reg_content.txt)
+          REGISTRY_PASS=$(jq -r '.REGISTRY_PASS' reg_content.txt)
+          ACR_FULL_NAME=$(jq -r '.ACR_FULL_NAME' reg_content.txt)
+          ACR_NAME=$(jq -r '.ACR_NAME' reg_content.txt)
 
-      - name: checkout
-        uses: actions/checkout@v5
-        with:
-          fetch-depth: 0
-      - name: setear docker
-        uses: docker/setup-buildx-action@v3
-        with:
-            install: true
-            
-      - name: Login to Azure Container Registry Andreani
-        if: ${{ inputs.andreani }}
-        uses: azure/docker-login@v1
-        with:
-          login-server: ${{ inputs.ACR_FULL_NAME }}
-          username: ${{ inputs.ACR_USERNAME }}
-          password: ${{ inputs.ACR_PASSWORD }}
+          echo "ACR_USERNAME=$ACR_USERNAME" >> "$GITHUB_ENV"
+          echo "ACR_PASSWORD=$ACR_PASSWORD" >> "$GITHUB_ENV"
+          echo "REGISTRY_PASS=$REGISTRY_PASS" >> "$GITHUB_ENV"
+          echo "ACR_FULL_NAME=$ACR_FULL_NAME" >> "$GITHUB_ENV"
+          echo "ACR_NAME=$ACR_NAME" >> "$GITHUB_ENV"
+          rm -f reg_content.txt
 
+          printf '%s' "$REGISTRY_DATA2" > reg_content.txt
+          ECR_ID=$(jq -r '.ECR_ID' reg_content.txt)
+          ECR_PASSWORD=$(jq -r '.ECR_PASSWORD' reg_content.txt)
+          ECR_FULLNAME=$(jq -r '.ECR_FULLNAME' reg_content.txt)
+          echo "ECR_ID=$ECR_ID" >> "$GITHUB_ENV"
+          echo "ECR_PASSWORD=$ECR_PASSWORD" >> "$GITHUB_ENV"
+          echo "ECR_FULLNAME=$ECR_FULLNAME" >> "$GITHUB_ENV"     
+          rm -f reg_content.txt
 
+          printf '%s' "$REGISTRY_DATA3" > reg_content.txt
+          ACR_USERNAMEWW=$(jq -r '.ACR_USERNAME' reg_content.txt)
+          ACR_PASSWORDWW=$(jq -r '.ACR_PASSWORD' reg_content.txt)
+          REGISTRY_PASSWW=$(jq -r '.REGISTRY_PASS' reg_content.txt)
+          ACR_FULL_NAMEWW=$(jq -r '.ACR_FULL_NAME' reg_content.txt)
+          ACR_NAMEWW=$(jq -r '.ACR_NAME' reg_content.txt)
+          echo "ACR_USERNAMEWW=$ACR_USERNAMEWW" >> "$GITHUB_ENV"
+          echo "ACR_PASSWORDWW=$ACR_PASSWORDWW" >> "$GITHUB_ENV"
+          echo "REGISTRY_PASSWW=$REGISTRY_PASSWW" >> "$GITHUB_ENV"
+          echo "ACR_FULL_NAMEWW=$ACR_FULL_NAMEWW" >> "$GITHUB_ENV"
+          echo "ACR_NAME=$ACR_NAMEWW" >> "$GITHUB_ENV"
+          rm -f reg_content.txt
 
-      - name: Build and push
-        uses: docker/build-push-action@v5
-        with:
-          context: . 
-          file: Dockerfile 
-          push: true
-          tags: |
-            ${{ steps.tags.outputs.result }}
+          printf '%s' "$REGISTRY_DATA4" > reg_content.txt
+          ECR_IDHOP=$(jq -r '.ECR_ID' reg_content.txt)
+          ECR_PASSWORDHOP=$(jq -r '.ECR_PASSWORD' reg_content.txt)
+          ECR_FULLNAMEHOP=$(jq -r '.ECR_FULLNAME' reg_content.txt)
+          echo "ECR_IDHOP=$ECR_IDHOP" >> "$GITHUB_ENV"
+          echo "ECR_PASSWORDHOP=$ECR_PASSWORDHOP" >> "$GITHUB_ENV"
+          echo "ECR_FULLNAMEHOP=$ECR_FULLNAMEHOP" >> "$GITHUB_ENV"
+          rm -f reg_content.txt
+        else
+          echo "::error::Tipo de workflow desconocido: $WORKFLOW"
+          exit 1
+        fi
+    - name: Obtengo datos de la aplicación
+      id: setOutputs
+      shell: bash
+      env:
+        APPDATA_JSON: ${{ inputs.appdataJson }}
+      run: |
+        APP_NAME=$(echo "$APPDATA_JSON" | jq -r '.appdata.appname')
+        PROJECT_NAME=$(echo "$APPDATA_JSON" | jq -r '.appdata.projectName')
+        CHART_NAME="${PROJECT_NAME}-${APP_NAME}"
+        echo "Obtenido nombre de app: ${APP_NAME}"
+        echo "Obtenido proyecto: ${PROJECT_NAME}"
+        echo "Obtenido chart-name: ${CHART_NAME}"
+        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
+        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
+        echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
+    #Genero los tags a pushear a ACR
+    - name: Generate ACR Andreani Tags 
+      if: ${{ inputs.WORKFLOW_CD == 'standard' || inputs.WORKFLOW_CD == 'multiorg' || inputs.WORKFLOW_CD == 'dms' }}
+      id: acrAndreaniTags
+      uses: actions/github-script@v8
+      with:
+        script: |
+          let tags = [];
+          let matrix_deploy = ${{ inputs.matrix_deploy }};
+          if (matrix_deploy.length > 0) {
+            matrix_deploy.forEach(deploy => {
+              let tag = `${{ env.ACR_FULL_NAME }}/${{env.CHART_NAME}}-${deploy}:${{ inputs.appVersion}}`
+              tags.push(tag);
+            });
+          } else {
+            tags.push(`${{ env.ACR_FULL_NAME }}/${{env.CHART_NAME}}:${{ inputs.appVersion}}`);
+          }
+          tags.push(`${{ env.ACR_FULL_NAME }}/${{env.CHART_NAME}}:ultima`);
+          return tags.join('\n');
+        result-encoding: string
 
-      - name: Login to Azure Container Registry Witwot
-        if: ${{ inputs.witwot }}
-        uses: azure/docker-login@v1
-        with:
-          login-server: ${{ inputs.ACR_FULL_NAMEWW }}
-          username: ${{ inputs.ACR_USERNAMEWW }}
-          password: ${{ inputs.ACR_PASSWORDWW }}
+    - name: Generate ACR Witwot Tags #TODO Usar estos tags para pushear a la registry de witwot en MultiOrg y hacerlo compatible con matrix_deploy
+      if: ${{ inputs.WORKFLOW_CD == 'witwot' || inputs.WORKFLOW_CD == 'multiorg' }}
+      id: acrWitwotTags
+      uses: actions/github-script@v8
+      with:
+        script: |
+          let tags = [];
+          let matrix_deploy = ${{ inputs.matrix_deploy }};
+          if (matrix_deploy.length > 0) {
+            matrix_deploy.forEach(deploy => {
+              let tag = `${{ env.ACR_FULL_NAME }}/${{env.CHART_NAME}}-${deploy}:${{ inputs.appVersion}}`
+              tags.push(tag);
+            });
+          } else {
+            tags.push(`${{ env.ACR_FULL_NAME }}/${{env.CHART_NAME}}:${{ inputs.appVersion}}`);
+          }
+          return tags.join('\n');
+        result-encoding: string
 
-#tags.push(`witwotcr.azurecr.io/${{inputs.teamProject}}-${{inputs.appName}}:${{ inputs.appVersion}}`);
-      - name: Push image to Azure Container Registry Witwot
-        if: ${{ inputs.witwot }}
-        shell: bash
-        run: |
-          docker buildx imagetools create \
-            --tag witwotcr.azurecr.io/${{inputs.teamProject}}-${{inputs.appName}}:${{ inputs.appVersion}} \
-            ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}:ultima
+    - name: Generate ECR hop Tags #TODO Usar estos tags para pushear a la registry de hop en MultiOrg y hacerlo compatible con matrix_deploy
+      if: ${{ inputs.WORKFLOW_CD == 'hop' || inputs.WORKFLOW_CD == 'multiorg' }}
+      id: ecrHopTags
+      uses: actions/github-script@v8
+      with:
+        script: |
+          REPOSITORY_URI=public.ecr.aws/hopenvios-sbx/${{env.CHART_NAME}}
+          let tags = [];
+          let matrix_deploy = ${{ inputs.matrix_deploy }};
+          if (matrix_deploy.length > 0) {
+            matrix_deploy.forEach(deploy => {
+              let tag = `${REPOSITORY_URI}-${deploy}:${{ inputs.appVersion}}`
+              tags.push(tag);
+            });
+          } else {
+            tags.push(`${REPOSITORY_URI}:${{ inputs.appVersion}}`);
+          }
+          tags.push(`${REPOSITORY_URI}:ultima`);
+          return tags.join('\n');
+        result-encoding: string
 
-#tags.push(`public.ecr.aws/hopenvios-sbx/${{inputs.teamProject}}-${{inputs.appName}}:${{ inputs.appVersion}}`);
+    - name: "Debug echos"
+      id: showtags
+      shell: bash
+      run: |
+            echo "Tags ACR Andreani Creados"
+            echo "${{ steps.acrAndreaniTags.outputs.result }}"
+            echo "Tags ACR Witwot Creados"
+            echo "${{ steps.acrWitwotTags.outputs.result }}"
+            echo "Tags ECR Hop Creados"
+            echo "${{ steps.ecrHopTags.outputs.result }}"
 
+    - name: checkout
+      uses: actions/checkout@v6
+      with:
+        fetch-depth: 0
 
-      - name: Login to Huawei SWR
-        if: ${{ inputs.witwot }}
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ inputs.SWR_URL }}
-          username: ${{ inputs.SWR_USERNAME }}
-          password: ${{ inputs.SWR_PASSWORD }}
-      - name: Push image to Huawei SWR
-        if: ${{ inputs.witwot }}
-        shell: bash
-        run: |
-          docker buildx imagetools create \
-            --tag ${{ inputs.SWR_URL }}/${{ inputs.SWR_NAME }}/${{ inputs.teamProject }}-${{ inputs.appName }}:${{ inputs.appVersion }} \
-            ${{ inputs.ACR_FULL_NAME }}/${{ inputs.teamProject }}-${{ inputs.appName }}:ultima
+    - name: Configurar BuildX para manejar multiples imagenes
+      uses: docker/setup-buildx-action@v4
+      with:
+        install: true
+
+# Build y push para casos de Andreani       
+    - name: Login to Azure Container Registry Andreani
+      if: ${{ inputs.WORKFLOW_CD == 'standard' || inputs.WORKFLOW_CD == 'multiorg' || inputs.WORKFLOW_CD == 'dms' }}
+      uses: azure/docker-login@v2
+      with:
+        login-server: ${{ env.ACR_FULL_NAME }}
+        username: ${{ env.ACR_USERNAME }}
+        password: ${{ env.ACR_PASSWORD }}
+
+    - name: Build and push Andreani
+      if: ${{ inputs.WORKFLOW_CD == 'standard' || inputs.WORKFLOW_CD == 'multiorg' || inputs.WORKFLOW_CD == 'dms' }}
+      uses: docker/build-push-action@v7
+      with:
+        context: . 
+        file: Dockerfile 
+        push: true
+        tags: |
+          ${{ steps.acrAndreaniTags.outputs.result }}
+
+# Build y push para casos de Witwot 
+    - name: Login to Azure Container Registry Witwot
+      if: ${{ inputs.WORKFLOW_CD == 'witwot' || inputs.WORKFLOW_CD == 'multiorg' }}
+      uses: azure/docker-login@v2
+      with:
+        login-server: ${{ env.ACR_FULL_NAMEWW }}
+        username: ${{ env.ACR_USERNAMEWW }}
+        password: ${{ env.ACR_PASSWORDWW }}
+
+    - name: Build and push Witwot
+      if: ${{ inputs.WORKFLOW_CD == 'witwot' }}
+      uses: docker/build-push-action@v7
+      with:
+        context: . 
+        file: Dockerfile 
+        push: true
+        tags: |
+          ${{ steps.acrWitwotTags.outputs.result }}
+
+    - name: Push image to extra-registry multiorg para Witwot #TBD - Por ahora multiorg No es compatible con multi-instancias (matrix-deploy)
+      if: ${{ inputs.WORKFLOW_CD == 'multiorg' }}
+      shell: bash
+      run: |
+        docker buildx imagetools create \
+          --tag ${{ env.ACR_FULL_NAMEWW }}/${{ env.CHART_NAME }}:${{ inputs.appVersion}} \
+          ${{ env.ACR_FULL_NAME }}/${{ env.CHART_NAME }}:ultima
+
+# Build y push para casos de HOP
+    - name: AWS Login to ECR
+      run: |
+        aws configure set aws_access_key_id ${{ env.ECR_IDHOP }}
+        aws configure set aws_secret_access_key ${{ env.ECR_PASSWORDHOP }}
+        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
+    
+    - name: Ensure ECR Repository Exists
+      env:
+        AWS_REGION: us-east-1
+      run: |
+        REPOSITORY_NAME="${{ env.CHART_NAME }}"
+        aws ecr-public describe-repositories --repository-names "$REPOSITORY_NAME" --region $AWS_REGION || \
+        aws ecr-public create-repository --repository-name "$REPOSITORY_NAME" --region $AWS_REGION
+        # Obtener el URI completo del repositorio público real
+        URI=$(aws ecr-public describe-repositories --repository-names "$REPOSITORY_NAME" --region $AWS_REGION --query 'repositories[0].repositoryUri' --output text)
+        echo "URI=$URI" >> $GITHUB_ENV
+
+    - name: Build and push hop
+      if: ${{ inputs.WORKFLOW_CD == 'hop' }}
+      uses: docker/build-push-action@v7
+      with:
+        context: . 
+        file: Dockerfile 
+        push: true
+        tags: |
+          ${{ steps.ecrHopTags.outputs.result }}
+
+    - name: Push image to extra-registry multiorg para hop #TBD - Por ahora multiorg No es compatible con multi-instancias (matrix-deploy)
+      if: ${{ inputs.WORKFLOW_CD == 'multiorg' }}
+      shell: bash
+      run: |
+        docker buildx imagetools create \
+          --tag ${{ env.URI }}:${{ inputs.appVersion}} \
+          ${{ env.ACR_FULL_NAME }}/${{ env.CHART_NAME }}:ultima
+#TODO SWR
+#    - name: Login to Huawei SWR
+#      uses: docker/login-action@v3
+#      with:
+#        registry: ${{ inputs.SWR_URL }}
+#        username: ${{ inputs.SWR_USERNAME }}
+#        password: ${{ inputs.SWR_PASSWORD }}
+#
+#    - name: Push image to Huawei SWR
+#      shell: bash
+#      run: |
+#        docker buildx imagetools create \
+#          --tag ${{ inputs.SWR_URL }}/${{ inputs.SWR_NAME }}/${{ inputs.teamProject }}-${{ inputs.appName }}:${{ inputs.appVersion }} \
+#          ${{ inputs.ACR_FULL_NAME }}/${{ inputs.teamProject }}-${{ inputs.appName }}:ultima
