Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -44,7 +44,12 @@ inputs:
   clusterFqdn:
      description: "FQDN para pasarle a helm"
      required: true
-
+  GITHUB_HELMREPO_TOKEN:
+    description: "Token para descargar el codigo de templates HELM"
+    required: true
+  appVersionGit:
+     description: "VersionGit"
+     required: true
       
 #env:
   #Es un valor que viene del secreto, pero el install de helm lo espera cmo variable 'plana'
@@ -121,38 +126,38 @@ runs:
           for i in {1..10}
           do
           if eval "$argoCommand"; then
-              echo "ArgoCD login OK"
+              echo "ArgoCD Project create OK"
               variableOk=1
               break
              else
-               echo "ArgoCD login $i/10"
+               echo "ArgoCD Project create $i/10"
                sleep 20
              fi
           done
           if [[ $variableOk != "1" ]]
           then
-              echo "Error en ArgoCD Login" >&2;
+              echo "Error en ArgoCD Project create" >&2;
               exit 1
           fi
 
           echo 'creacion app argocd'
           variableOk=0
-          argoCommand="argocd app create ${{inputs.teamProject}}-${{inputs.appName}}-qa --repo ${{ inputs.ACR_FULL_NAME }} --helm-chart helm/${{inputs.teamProject}}-${{inputs.appName}} --upsert --helm-set Chart.yaml=Chart.yaml --helm-set-file values.yaml=values.yaml --helm-set-file Chart.yaml=Chart.yaml --revision ${{ inputs.helmChartVersionLatestQa}} --dest-namespace ${{inputs.teamProject}}-qa --dest-server https://kubernetes.default.svc --sync-policy auto --auto-prune --self-heal --project ${{inputs.teamProject}}-qa --grpc-web"
+          argoCommand="argocd app create ${{inputs.teamProject}}-${{inputs.appName}}-qa --repo ${{ inputs.ACR_FULL_NAME }}/helm --helm-chart ${{inputs.teamProject}}-${{inputs.appName}} --upsert --helm-set Chart.yaml=Chart.yaml --helm-set-file values.yaml=values.yaml --helm-set-file Chart.yaml=Chart.yaml --revision ${{ inputs.helmChartVersionLatestQa}} --dest-namespace ${{inputs.teamProject}}-qa --dest-server https://kubernetes.default.svc --sync-policy auto --auto-prune --self-heal --project ${{inputs.teamProject}}-qa --grpc-web"
           
           for i in {1..10}
           do
           if eval "$argoCommand"; then
-              echo "ArgoCD login OK"
+              echo "ArgoCD app create OK"
               variableOk=1
               break
              else
-               echo "ArgoCD login $i/10"
+               echo "ArgoCD app create $i/10"
                sleep 20
              fi
           done
           if [[ $variableOk != "1" ]]
           then
-              echo "Error en ArgoCD Login" >&2;
+              echo "Error en ArgoCD app create" >&2;
               exit 1
           fi
           
@@ -177,17 +182,17 @@ runs:
           for i in {1..10}
           do
           if eval "$argoCommand"; then
-              echo "ArgoCD login OK"
+              echo "ArgoCD sync OK"
               variableOk=1
               break
              else
-               echo "ArgoCD login $i/10"
+               echo "ArgoCD sync $i/10"
                sleep 20
              fi
           done
           if [[ $variableOk != "1" ]]
           then
-              echo "Error en ArgoCD Login" >&2;
+              echo "Error en ArgoCD sync" >&2;
               exit 1
           fi
 
